//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM2AGENDA
    {
        public int Id { get; set; }
        public long item { get; set; }
        public int type { get; set; }
        public int agenda { get; set; }
        public string description { get; set; }
        public System.DateTime lastUpdate { get; set; }
        public decimal opinion { get; set; }
        public decimal importance { get; set; }
    }
}
