//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MK_SCORE
    {
        public int Id { get; set; }
        public int mk { get; set; }
        public decimal score { get; set; }
        public decimal volume { get; set; }
        public System.DateTime fromDate { get; set; }
        public System.DateTime toDate { get; set; }
        public int agendaId { get; set; }
    
        public virtual MK MK1 { get; set; }
        public virtual AGENDA AGENDA { get; set; }
    }
}
