//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VOTE()
        {
            this.VOTE_TO_AGENDA = new HashSet<VOTE_TO_AGENDA>();
        }
    
        public int Id { get; set; }
        public System.DateTime meeting { get; set; }
        public Nullable<int> bill { get; set; }
        public Nullable<int> mk { get; set; }
        public int vote1 { get; set; }
        public Nullable<int> source { get; set; }
    
        public virtual BILL BILL1 { get; set; }
        public virtual MK MK1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOTE_TO_AGENDA> VOTE_TO_AGENDA { get; set; }
    }
}
